services:
  - type: web
    name: pi-devsft
    env: python
    buildCommand: "pip install -r requirements.txt"
    # ¡IMPORTANTE! Cambia el startCommand
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pi-devsft-db
          property: connectionString
databases:
  - name: pi-devsft-db
    databaseName: pi_dev_db
    user: pi_user
